permalink:  /:year/:month/:title/
highlighter: rouge
safe: true
future: false
lsi: false
markdown: kramdown
url: http://chrismdp.com
repository: chrismdp/chrismdp.github.com
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
