# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chris Parsons
email: chris.p@rsons.org
author: Chris Parsons
logo: /assets/img/chris-1.9-1.jpg
description: |
  Hi, I'm Chris. I'm co-founder/CTO of Cherrypick, the best meal-led AI-driven grocery shopping assistant on the market. I spend some of my time coaching and advising tech founders, teams and businesses - get in touch if you're interested.

# This is mostly for testing
url: "https://chrismdp.com" # the base hostname & protocol for your site

# Add colorful permalinks to headers
# change colors in _includes/permalinks.html
add_permalinks: true

# Optional
twitter: chrismdp
bluesky: chrismdp.com
linkedin: chrisparsons
repo: https://github.com/chrismdp/chrismdp.github.com
github_user: chrismdp
github_repo: chrismdp.github.com

# branch to edit on GitHub
github_branch: master

# If not set, badge color (background) defaults to violet
# badge_color: "#2bcf98"
badge_rounded: true

# If you add tags to pages, define this variable to link them to some external search
# If you want to link to tags locally on the site, leave this commented out
# tag_search_endpoint: https://ask.cyberinfrastructure.org/search?q=
tag_color: primary # danger, success, warning, primary, info, secondary

accentColor: red # purple, green, etc.
themeColor: red # purple, green, blue, orange, purple, grey
fixedNav: 'true' # true or false

permalink: /:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md, vendor]

excerpt_separator: <!--more-->

# Collections
# collections:
#   docs:
#     output: true
#     permalink: /:collection/:path

# Defaults

safe: true
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
